### ISSUE TITLE
Menu Changes for Project Panel and Cohort Builder

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#964]
Considering so much of RDMP is controlled via the "right click menu" there are a couple of naming scheme suggestions and conventions that should be considered.

Right click menu options  should follow conventions:
1. More common/typical options should be a the top (e.g. Add,Edit,View Data,Graph)
2. Commands that will _never_ be enabled for that object ,from a users perspective, (e.g. 'Edit' for an 'AggreateDimension') the option should be removed.
4. For common commands such as "Add" a folder should be created (i.e. Add, Graph)
5. Sub commands should not include an add or create prefix
6. When adding a link/copy of another/existing object they should use the "Existing" prefix then end with "copy of" or "link to" depending on the type of import.
7. Where only one sub command exists it should still be placed in it's folder for Add and Graph to be consistent and draw user attention
8. Where only one "group" of options exist (e.g. you can only "Add") then they should NOT be nested unless the available options are dynamic - i.e. there is only "add" options available at the moment but that might change in a different state. This is because we don't need to draw attention to these important commands because it's the only options available. These options SHOULD include an "Add" prefix.

- [x] Additionally common right click options that need grouped: (https://github.com/HicServices/RDMP/issues/782)
  - Disable (to avoid it being next to delete) - 50.1
  - Rename - 50.2
  - Go To... - 50.3 - changed in ExecuteCommandSimilar and ExecuteCommandShow
  - Delete - 50.4

- [x] The "favourites" menu options should also be re-ordered to the following: (https://github.com/HicServices/RDMP/issues/961)
  - Favourite - 100.1
  - Add to Session - 100.2
  - Inspection (although this should be removed if it's never available on the object) 100.3 (weight added via ExecuteCommandCheckAsync and check added to RDMPContextMenuStrip line 170 to check if this menu item should be added or not)
  - Tree - 100.4
  - Refresh Object - 100.5
  - What is This? - 100.6

# Project Panel
- [x] Change the "New" menu to be as follows:
  - Project
  - __
  - Cohort Builder Query
  - Cohort
    - From Cohort Builder Query
    - From File
    - From Catalogue
  - __
  - Extraction Configuration
  - __
  - Project Specific Catalogue
  - Package
- [x] Update right clicking on white space menu to be the same as the "New" menu options
- [x] Right Click on a `Project` should be:
  - Edit
  - Run Extraction Configuration
  - Run Release
  - Add
     - New Cohort Builder Query
     - __
     - New Cohort from Cohort Builder Query
     - New Cohort from File
     - New Cohort from Catalogue
    - __
    - New Extraction Configuration
    - __
    - New Project Specific Catalogue
  - __
  - Common Disable/Fav menus 
- [x] Right click menu for `Cohort` folder - remove `Edit` option as this is never available
  - Add New Cohort Builder Query
  - Add Existing Cohort Builder Query (link to)
  - __
  - Add New Cohort from Cohort Builder Query
  - Add New Cohort from Catalogue
  - Add New Cohort from File
- [x] Right click menu for `Cohort Builder Queries`
  - Remove Edit option
  - Add New Cohort Builder Query
  - Add Existing Cohort Builder Query (link to)
  - __
  - Common Disable/Fav menus 
- [x] Right click menu for `Saved Cohorts` 
  - Remove Edit option
  - Add New Cohort from Cohort Builder Query
  - Add New Cohort from Catalogue
  - Add New Cohort from File
  - __
  - Common Disable/Fav menus 
- [x] Right click menu for `Extraction Configurations`
  - Remove Edit option
  - Run Extraction Configuration
  - Run Release
  - __
  - Add New Extraction Configuration
  - __
  - Common Disable/Fav menus 
  - [x] Right click menu for `Forzen Extraction Configurations`
    - Remove Edit option
    - Common Disable/Fav menus 
  - [x] Right click menu for `Project Specific Catalogues`
    - Remove Edit option
    - Add Existing Catalogue (also update the popup to include description about what's happening)
    - Add New Catalogue from File
    - Add New Catalogue from Existing Database Table

**Elements within the folder structure also need their menus updated:**

- [x] For `ProjectCohortIdentificationConfigurationAssociation`:
  - Edit
  - Commit Cohort
  - View
    - Query Builder SQL/Results
    - Query Builder SQL/Results (no cache)
  - __
  - Freeze/Unfreeze
  - Clone
  - Associate with Project
  - Change Query Cache
  - __
   - Common Disable/Fav menus 

- [x] For `CohortSourceUsedByProjectNode`
  - Edit
  - Show Cohort Summary
  - Add
    - New Cohort from Cohort Builder Query
    - New Cohort from Catalogue
    - New Cohort from File
    - Existing Cohort (copy of)
    - __
    - Common Disable/Fav menus 

- [x] For the `Saved Cohorts themselves...`:
  - Edit
  - View Cohort Sample
  - Save Cohort To File...
  - Deprecate Cohort / Undeprecate Cohort
  - __
  - Common Disable/Fav menus 

- [x] `ExtractionConfiguration` within the `Extraction Configurations` folder:
  - Configure/Run Extract
  - Add
    - Existing Cohort
    - Existing Datasets/Packages
    - New Extract Filter Parameter
  - Release
  - Generate Release Document
  - Edit
  - __
  - View Logs
  - Open Extraction Directory
  - __
  - Freeze/Unfreeze
  - Clone
  - __
  - Common Disable/Fav men

- [x] `SelectedDataSets`
  - Edit Extractable Columns
  - Set Extraction Identifier
  - Add
    - New Filter
    - Existing Filter (copy of)
    - __
    - New Filter Container
    - Existing Filter Container (copy of)
    - __
    - New Catalogue Filter Parameter
  - Batching
    - Add Extraction Progress
    - Reset Extraction Progress
  - __
  - Extract
  - Release
  - __
  - View Then vs. Now SQL
  - Graph
    - Sub graphs...
  - Open Extraction Directory...
  - __
  - Common Disable/Fav men

# Cohort Query Builder

For the `CohortIdentifcationConfiguration` the menu items are already described above for `ProjectCohortIdentificationConfigurationAssociation`

- [x] For the `QuieryCacheUsbedByCohortIdentificationNode`:
  - Edit
  - Clear Query Cache
  - View Data
  - __
   - Common Disable/Fav menus 

- [x] For `CohortAggregateContainer`:
  - Add
    - Catalogue - 0.11
    - Sub Container - 0.12
    - Aggregate  0.13
    - Existing Cohort Set (copy of) - 0.14
    - Existing Cohort Builder Query (copy of) - 0.15
  - Set Operation 
    - UNION - 0.21
    - EXCEPT - 0.22
    - INTERCEPT - 0.23
  - Separate Cohort Builder Query (we're not undoing a merge, we're separating what we've created) - 0.3
  - Graph - modified ExecuteCommandViewCohortAggregateGraph to be Weight 0.4
  - __
   - Common Disable/Fav menus 
  - __
  - View Results
  - View SQL
  - View Build Log
  - View Crash Messages
  - Clear Object From Cache

- [x] For `AggregateConfiguration`:
  - Add
    - New Filter
    - Existing Filter
    - __
    - New Filter Container
    - Existing Filter Container (copy of)
    - __
    - New Catalogue Filter Parameter
  - View Sample SQL/Data (change to do not auto run, and resize top window to be more SQL focused)
  - Graph
    - Results
    - Cohort
    - Full Catalogue
   - __
   - Common Disable/Fav menus

Additionally, note that:
- [x] "Dimensions" should be removed from right click menu for this item
- [x] "Create New Catalogue by Executing an Aggregate Configuration" will be removed because this is misleading to what it does from here.
- [x] "Set Filter Tree Shortcut"/"Clear Filter Tree Shortcut" will also be removed until it is more functional and obvious what is happening
- [x] When adding an existing filter you should be able to select multiple filters from the list (#965)

- [ ] For `AggregateFilterContainer`:
  - Add
    - New Filter
    - Existing Filter
    - New Sub Container
  - Set Operation
    - AND
    - OR
  - View Extract
  - View Aggregate (can we make these more consistent with the "View Sample/SQL Data" options?
  - __
  - Common Disable/Fav menus 

- [x] For `AggregateFilterParameter`:
  - Edit Value
  - Edit Parameter SQL
  - __
  - Common Disable/Fav menus 

- [x] For `AggretateDimension`:
  - Common Disable/Fav menus

**Comment by tznind** [comment]
Fixed in #973
