### ISSUE TITLE
Update project specific catalogues to be more informative to the user/less visually broken

### ISSUE THREAD

**Issue by RoyMudie** [HicServices/RDMP#999]
**Is your feature request related to a problem? Please describe.**
Project Specific catalogues have two main problems:

1. The icon is cumbersome in that it uses two ways to tell the user it is project specific, namely: a P icon overlay and change of colour to green.
2. A catalogue only tells the user that it is project with this icon. There is information about what project it is in the tool tip or Catalogue editor UI.

**Describe the solution you'd like**

- [x] Clean up the icon by removing the P overlay (done in #1001 )
- [x] Add project information to tooltip (done in #1001 )
- [x] Add project information / link to the CatalogueUI (done in #1001 )
